# Generated by Django 5.2.10 on 2026-01-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
